### ISSUE TITLE
要怎麼控制每一篇文章的預覽行數？

### ISSUE THREAD

**Issue by mosdeo** [stkevintan/hexo-theme-material-flow#28]
在首頁，每一篇文章都展開太多。我希望可以一個 block 的預覽行數，如果每一個 block 能夠個別設定的話更好。

**Comment by stkevintan** [comment]
可以使用webkit的私有css属性: `-webkit-line-clamp` 比如说，在本主题的css里面添加如下规则： 
```css
.post-list .article{
  display: -webkit-box;
  -webkit-line-clamp: 8;
}
```
