### ISSUE TITLE
Search does not work for categories and tags

### ISSUE THREAD

**Issue by ghost** [stkevintan/hexo-theme-material-flow#29]
Search does not work for categories and tags. It does not find anything.

I specified one category as "HOUSE" and many posts have category "HOUSE", but
when I search for "HOUSE", then zero results.

Same problem with tags.

How solve? Everything else works and search is enabled true.

**Comment by stkevintan** [comment]
edit your global `_config.yml` :  
```yaml
# Generator json content
jsonContent:
  meta: false
  keywords: false
  pages:
    title: true
    slug: false
    date: false
    updated: false
    comments: false
    path: false
    link: false
    permalink: true
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
  posts:
    title: true
    slug: false
    date: false
    updated: false
    comments: false
    path: false
    link: false
    permalink: true
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
    categories: false
    tags: false
```
set `categories` and `tags` to `true` . regenerate your site and the things should be ok.
